In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [3]:
#### 2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)
print(np.show_config())

1.21.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ingae/anaconda3/envs/DA_Envi\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ingae/anaconda3/envs/DA_Envi\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ingae/anaconda3/envs/DA_Envi\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ingae/anaconda3/envs/DA_Envi\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ingae/anaconda3/envs/DA_Envi\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/ingae/anaconda3/envs/DA_Envi\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/ingae/anaconda3/envs/DA_Envi\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = [

In [5]:
#### 3. Create a null vector of size 10 (★☆☆)
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#### 4. How to find the memory size of any array (★☆☆)
null_vector.size

10

In [10]:
#### 5. How to get the documentation of the numpy add function from the command
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [14]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_one_vector=np.zeros(10); null_one_vector[4]=1
null_one_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [21]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
range_array=np.arange(10,50)
range_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
reverse_vector=range_array[::-1]
reverse_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [25]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix=np.arange(0,9).reshape((3, 3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#### 10. Find indices of non-zero elements from (★☆☆)
no_zero= [1,2,0,0,4,0]
np.nonzero(no_zero)

(array([0, 1, 4], dtype=int64),)

In [40]:
#### 11. Create a 3x3 identity matrix (★☆☆)
ident_matrix=np.identity(3)
print(ident_matrix)

eye_matrix=np.eye(3)
print('\n', eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
threeD=np.random.random(size=(3,3,3))
threeD

array([[[0.52294087, 0.35257219, 0.32155393],
        [0.49476024, 0.50926935, 0.30169517],
        [0.68791537, 0.65941737, 0.30598398]],

       [[0.51305451, 0.70615806, 0.66979816],
        [0.29711988, 0.89385459, 0.87886426],
        [0.96422018, 0.60533877, 0.92807932]],

       [[0.97999784, 0.92313132, 0.55996326],
        [0.54359262, 0.62585232, 0.11773343],
        [0.19771582, 0.91887346, 0.07878439]]])

In [57]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
MM_array=np.random.random(size=(10,10))
#print(MM_array)

mini=np.min(MM_array)
print(mini)

maxi=np.max(MM_array)
print(maxi)

0.03777864122925889
0.996842362513813


In [61]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
rand_vec=np.random.random(size=(30))
#print(rand_vec)
np.mean(rand_vec)

0.5302316543307422

In [68]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
zero_array=np.ones((3,3));zero_array[1:-1, 1:-1]=0  #[1:-1, 1:-1] from row 2 to 2nd last, and 2nd column to 2nd last
zero_array

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [72]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
zero_array2=np.pad(zero_array, pad_width=1, mode='constant', constant_values=0)
zero_array2

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
#### 17. What is the result of the following expression? (★☆☆)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
x=3*0.1
print(x)
np.multiply(3,0.1)

nan
False
False
nan
True
0.30000000000000004


0.30000000000000004

In [84]:
### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

dia_matrix= np.diag(1+np.arange(4),k=-1)
print(dia_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [106]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
checkerboard = np.zeros((8,8),dtype=int)
checkerboard[1::2,0::2] = 1
checkerboard[0::2,1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [104]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [107]:
### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
tile_matrix= np.tile( np.array([[0,1],[1,0]]), (4,4))
print(tile_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [113]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
norm_matrix = np.random.random((5,5))
norm_matrix2= (norm_matrix  - np.mean (norm_matrix )) / (np.std (norm_matrix ))
print(norm_matrix2 )

print(np.mean(norm_matrix2))
print(np.std(norm_matrix2))

[[-0.96910714  0.11471572  0.24566043  1.1147718  -1.3934407 ]
 [ 0.41490873 -1.4201248   0.35479239  0.11177343 -0.33910414]
 [-1.57316492  0.67148626  1.44328767  1.25001234 -0.8924138 ]
 [ 1.07329231 -1.18671174  1.39601131  1.39264107  0.30383697]
 [-0.96754517 -0.64020953  0.60017202 -1.58590285  0.48036234]]
8.43769498715119e-17
1.0


In [114]:
#### 49. How to print all the values of an array? (★★☆)
np.set_printoptions(threshold=float("inf"))
R= np.zeros((40,40))
print(R)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [117]:
###  55. What is the equivalent of enumerate for numpy arrays? (★★☆)
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [118]:
### 83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7
